# Generated by Django 5.2.1 on 2025-05-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dono',
                'verbose_name_plural': 'Donos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('instrucoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Medicação',
                'verbose_name_plural': 'Medicações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Réptil'), ('OUTRO', 'Outro')], max_length=20)),
                ('raca', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets_fotos/')),
                ('observacoes', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.dono')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.pet')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('MEDICACAO', 'Medicação'), ('VACINA', 'Vacina'), ('EXAME', 'Exame'), ('OUTRO', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField()),
                ('concluido', models.BooleanField(default=False)),
                ('notificar', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.pet')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=50)),
                ('frequencia', models.CharField(choices=[('1X', '1 vez ao dia'), ('2X', '2 vezes ao dia'), ('3X', '3 vezes ao dia'), ('4X', '4 vezes ao dia'), ('SEMANA', 'Semanal'), ('QUINZENA', 'Quinzenal'), ('MES', 'Mensal'), ('OUTRO', 'Outro')], max_length=20)),
                ('duracao', models.IntegerField(help_text='Duração em dias')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='core.consulta')),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicacao')),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['data_inicio'],
            },
        ),
    ]
