# Generated by Django 5.2 on 2025-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_missing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
