# Generated by Django 5.2 on 2025-08-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.CharField(choices=[('MV Paulo Alelúlia', 'MV Paulo Alelúlia'), ('MV Cleber Azevedon Souza', 'MV Cleber Azevedon Souza'), ('MV Ana Aarolina Piazza', 'MV Ana Aarolina Piazza'), ('MV Camila Banborra', 'MV Camila Banborra')], default='MV Paulo Alelúlia', max_length=100),
        ),
    ]
