# Generated by Django 5.2 on 2025-08-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consulta_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='veterinario',
            field=models.CharField(choices=[
                ('MV Paulo Alelúia', 'MV Paulo Alelúia'),
                ('MV Cleber Azevedo Souza', 'MV Cleber Azevedo Souza'),
                ('MV Ana Carolinna Piazza', 'MV Ana Carolinna Piazza'),
                ('MV Camila Banborra', 'MV Camila Banborra')
            ], default='MV Paulo Alelúia', max_length=100),
        ),
    ]
